### ISSUE TITLE
Dividir o readme.md em subarquivos

### ISSUE THREAD

**Issue by nicholasess** [IonicBrazil/guia-do-desenvolvedor#10]
Está ficando grande o arquivo, poderia ser dividido já em arquivos.
Pois chegará numa hora que a galera vai rolar scroll pra caramba e vai enjoar.

**Comment by juarezpaf** [comment]
@nicholasess uma ótima sugestão, vamos verificar uma forma bacana de fazer isso. :smile:

**Comment by felquis** [comment]
@nicholasess Eu sou mais a favor de fazer um Sumário assim como é feito neste Stye Guide, acho interessante porque abro 1 aba, e posso ficar offline que continuo lendo tudo sem precisar acessar links externos.

Talvez uma estrutura semelhante fosse interessante, ou até mesmo uma tarefa do Gulp que concatena vários markdown para apenas 1, colocando um link para o topo e outro para editar o source.

Algo assim

## Sugerimos usar X ou Y, mas preferência para X

[Ir para o topo](#link-para-a-hash-do-resumo) - [Melhor está sessão](#link-para-o-editor-do-github-online)

E assim vai! Faz build, e comita, assim como fazemos com github pages, só acho que o GitHub tem um design bonito de mais, para usarmos GitHub pages, porque aqui já é o melhor lugar para usar como uma home page, com comentários que são as issues, e por ai vai.

Inclusive poderiamos criar issues que correspondem as sessões, e colocar também um link para  a issue equivalente a sessão, ai se alguém tiver dúvida de algo, já pergunta e a galera engajada no `guia-do-desenvolvedor` já pode responder, melhor do que qualquer fórum, IRC e grupo de email na internet a fora.

Algo assim:

## Sugerimos usar X ou Y, mas preferência para X

[Ir para o topo](#link-para-a-hash-do-resumo) - [Melhor está sessão](#link-para-o-editor-do-github-online) - [Tirar dúvidas](#link-para-a-issue)

**Comment by nicholasess** [comment]
Pode ser @felquis, o que for melhor para a leitura, estou a favor.
Foi mais para abertura de discussões e ter melhorias para os dados

**Comment by raphaelpor** [comment]
Para dar o primeiro passo, o que acham de um simples sumário?

**Comment by giorgiofellipe** [comment]
@raphaelpor já é um começo :+1:

**Comment by raphaelpor** [comment]
Feito! rs
:rocket:
