### ISSUE TITLE
Style Guides

### ISSUE THREAD

**Issue by ivosantiago** [IonicBrazil/guia-do-desenvolvedor#14]
Eu pensei em adicionar uma sessão de Style Guides no documento mas tenho algumas dúvidas:
1. Deveríamos ser mais genéricos e recomendar Style Guides de javascript [como esse do Airbnb](https://github.com/airbnb/javascript) ou sermos mais específicos e usarmos esse do [John Papa](https://github.com/johnpapa/angular-styleguide) ou esse do [Todd Motto](https://github.com/toddmotto/angularjs-styleguide)?
2. Vocês conhecem alguma referência boa em português pra ser adicionada também?

**Comment by juarezpaf** [comment]
@ivosantiago poderíamos traduzir esses Guides e depois adicioná-los aqui. o/

**Comment by felquis** [comment]
Na real, esses repositórios já são traduzidos, o https://github.com/johnpapa/angular-styleguide é muito bom. E foi traduzido por brothers, podemos quem sabe dar uma revisada e atualiza-lo.

**Comment by felquis** [comment]
Lembrando de recomendar que as pessoas usem o mesmo `.jscsrc` que o AngularJS usa, o Ionic usa o mesmo que o AngularJS também. Porém eu recomendo limitar para usar [apenas single quotes](http://jscs.info/rule/validateQuoteMarks.html)

O que vocês acham?  O que colocamos no README?

**Comment by ivosantiago** [comment]
@felquis posta os links das traduções aqui para darmos uma olhada. Eu reviso o que for preciso pra atualizar (se é que precisa) e posto o resultado aqui também

**Comment by felquis** [comment]
Lista de traduções aqui https://github.com/johnpapa/angular-styleguide/tree/master/i18n#translations

**Comment by juarezpaf** [comment]
Ótimo! @ivosantiago acho que podemos mudar um pouco o texto que fala o que é o Ionic e adicionar o angular style guide do John Papa. Vai ficar bem coerente, não vejo a necessidade de uma sessão para isso. :dancers:

**Comment by lucasbastianik** [comment]
Eu penso que se o Ionic está seguindo o style guide do Angular JS, não tem porque criarmos um próprio.. Então acho que fazer a referencia como o @juarezpaf disse, seja o mais coerente! ;)

**Comment by felquis** [comment]
@Galera No Ionic Garden já estamos passando por algo semelhante onde projetos Open Source não atendem o que precisamos fazer. O próprio Ionic está em evolução constante, e encontrei [está dificuldade com o JSCS](https://github.com/IonicBrazil/ionic-garden/issues/23#issuecomment-116342389)

Acredito que em alguns casos a organização IonicBrazil irá se unir para enviar pull requests para os projetos de fora, e inclusive forca-los e otimiza-los para as necessidades que temos com o Ionic.

@lucasbastianik Me passa o link para o Style Guide do Ionic/AngularJS por favor? Só encontrei referências ao arquivo `.jscsrc` deles e já estamos usando, inclusive estamos usando o Johnpapa's Style Guide e temos muito trabalho ainda para fazer no Ionic Garden, se a galera tiver disponibilidade e coragem para adotar alguma issue no repositório https://github.com/IonicBrazil/ionic-garden/issues

Inclusive, coragem para adotar issues relacionadas a este outro repositório aqui https://github.com/IonicBrazil/ionicbrazil.com
