### ISSUE TITLE
Adicionar versão logo de pernambuco

### ISSUE THREAD

**Issue by felquis** [IonicBrazil/guia-do-desenvolvedor#26]
Discutido no pull request https://github.com/IonicBrazil/guia-do-desenvolvedor/pull/25#issuecomment-114350821

Está versão https://github.com/IonicBrazil/guia-do-desenvolvedor/blob/master/resources/logos/brazil/ionic-brazil-logo.png 

Precisamos para pernambuco também https://github.com/IonicBrazil/guia-do-desenvolvedor/blob/master/resources/logos/pernambuco/ionic-pernambuco-logo.png

No #27 temos mais informações sobre o que precisa ser feito, e o set completo de imagens que precisamos para as organizações.

**Comment by breakzplatform** [comment]
Finalmente tive um tempinho pra fazer, dá uma olhada. Dá pra usar ela de base pra um guideline.

![ionic-pe](https://cloud.githubusercontent.com/assets/597126/8421555/f4997c9e-1ea6-11e5-9383-76527baf12a5.png)

**Comment by juarezpaf** [comment]
@joselitojunior manda o arquivo fonte para gente se deliciar. :heart_eyes:

**Comment by breakzplatform** [comment]
c60b031a4e4956caa0ea6bfbc8c85dadd9ddc017 fecha a issue
