### ISSUE TITLE
Design Style Guide para criar logos do Ionic por regiões

### ISSUE THREAD

**Issue by felquis** [IonicBrazil/guia-do-desenvolvedor#29]
@joselitojunior Poderia ver isso se não for pedir de mais? Imagino um README, dizendo Faca uma imagem de tamanho x por x, use a fonte X, com tamanho Y, e por ai vai.

O Ionic respondeu e disse qual é a fonte:
https://twitter.com/Ionicframework/status/613374215488573440

**Comment by breakzplatform** [comment]
:+1: pode deixar

**Comment by breakzplatform** [comment]
A equipe do Ionic disse que era a Avenir Next, eu também achava, porém observe a diferença entre a Avenir Next (em azul escuro) com o logo original:

![avenirnext](https://cloud.githubusercontent.com/assets/597126/8316133/58efc7ba-19cb-11e5-905b-2036c0ad787e.png)

Aparenta ser uma variação da Avenir, mas não ela própria. Quem fez o logo original para descobrirmos qual versão da Avenir é esta?

Update: Versão oficial da Avenir: http://www.fonts.com/font/linotype/avenir-next

**Comment by breakzplatform** [comment]
A fonte que deve ser utilizada é a Avant Garde. Mais detalhes ver o README de design style do logo em `logos/README.md`
