### ISSUE TITLE
Adicionar logo IonicBahia

### ISSUE THREAD

**Issue by juarezpaf** [IonicBrazil/guia-do-desenvolvedor#34]
Meetup: http://www.meetup.com/ionicbahia/
- [ ] Ajustar url para http://www.meetup.com/Ionic-Bahia/ e atualizar o `README.md`

![2000px-bandeira_da_bahia svg](https://cloud.githubusercontent.com/assets/21221/8492367/f84348c8-211e-11e5-8abb-f7e80679804d.png)

**Comment by juarezpaf** [comment]
O @joselitojunior e seu enorme <3 deu uma força, agora vocês podem por favor criar o Pull Request e verificar a questão da URL que coloquei na descrição dessa issue? thx
cc @IonicBrazil/bahia 

![ionic-bahia-icon](https://cloud.githubusercontent.com/assets/21221/8492475/ae3c90a2-2120-11e5-9936-0a8581c3b756.png)
![ionic-bahia-logo](https://cloud.githubusercontent.com/assets/21221/8492476/ae5a3e72-2120-11e5-969a-afae3b047f8e.png)

**Comment by felquis** [comment]
Boa, lembrem-se de colocar os arquivos no repositório, seguindo o padrão de tamanho e formato dos outros :D
