### ISSUE TITLE
Adicionar logo Ionic Rio de Janeiro

### ISSUE THREAD

**Issue by juarezpaf** [IonicBrazil/guia-do-desenvolvedor#35]
Meetup: http://www.meetup.com/Ionic-Rio-de-Janeiro/

![bandeira_do_estado_do_rio_de_janeiro svg](https://cloud.githubusercontent.com/assets/21221/8492427/d0272426-211f-11e5-8342-d1f3ad8d791f.png)

**Comment by juarezpaf** [comment]
@IonicBrazil/rio-de-janeiro não consegui contato com os organizadores do Meetup, alguém tem algum contato? o/

**Comment by rdiego26** [comment]
@juarezpaf Tenho o contato do Jefferson apenas no FB: https://www.facebook.com/eusouojeff

**Comment by juarezpaf** [comment]
Valeu @rdiego26 Mandei mensagem para ele lá! :dancers:
