### ISSUE TITLE
Arquivo Illustrator source para logos

### ISSUE THREAD

**Issue by breakzplatform** [IonicBrazil/guia-do-desenvolvedor#36]
Precisamos de um designer que manje de illustrator para fazer um arquivo padrão, facimente editável por qualquer um, com a finalidade de facilitar a padronização dos logos.

Relacionado com #32

**Comment by alvarowolfx** [comment]
Eu posso disponibilizar a versão que fiz com o Sketch @joselitojunior, está separado por Artboards, acha que ajuda ?  
<img width="948" alt="captura de tela 2015-07-03 as 12 00 30 am" src="https://cloud.githubusercontent.com/assets/1615543/8492371/af3ab2e0-2116-11e5-836d-56275915f0bc.png">
<img width="773" alt="captura de tela 2015-07-03 as 12 00 44 am" src="https://cloud.githubusercontent.com/assets/1615543/8492372/afaab77a-2116-11e5-8961-2e0c650f3649.png">

**Comment by juarezpaf** [comment]
@alvarowolfx ajuda sim! Mas por favor usa a fonte `avant garde` ;)

**Comment by alvarowolfx** [comment]
Mas @juarezpaf  de acordo com #29 a fonte é a Avenir Next, procede @joselitojunior ?

**Comment by breakzplatform** [comment]
@alvarowolfx, troca a fonte e manda um PR com o arquivo (coloca ele em logos/sources)

**Comment by alvarowolfx** [comment]
Ops, eu não vi o Tweet, só vi a discussão na Issue hahahah, vou mandar o PR

**Comment by juarezpaf** [comment]
@alvarowolfx se for mandar os arquivos do Sketch a hora é essa de fazer uma modificação no PR #40 \o/
