### ISSUE TITLE
Adicionar Ionic Rio Grande do Sul

### ISSUE THREAD

**Issue by juarezpaf** [IonicBrazil/guia-do-desenvolvedor#38]
Alguém tem o contato do organizer de lá http://www.meetup.com/Ionic-Framework-Porto-Alegre/
- [x] Sugestão: Alterar nome para _Ionic Rio Grande do Sul_

![bandeira_do_rio_grande_do_sul svg](https://cloud.githubusercontent.com/assets/21221/8492346/acdf0ca0-211e-11e5-9028-b2d82a515454.png)

**Comment by juarezpaf** [comment]
@IonicBrazil/moderadores alguém conhece o Marcel? http://www.meetup.com/Ionic-Framework-Porto-Alegre/members/189104642/

**Comment by silvamarcel** [comment]
Oi @juarezpaf, vou alterar, boa a sugestão.

**Comment by silvamarcel** [comment]
Feito!

**Comment by juarezpaf** [comment]
@silvamarcel Falta adicionar o logotipo na pasta e linkar no `README.md` ;)
