### ISSUE TITLE
Adicionar Ionic Ceará Meetup

### ISSUE THREAD

**Issue by juarezpaf** [IonicBrazil/guia-do-desenvolvedor#52]

**Comment by breakzplatform** [comment]
@vitormalencar só funciona na pressão :hammer:

**Comment by juarezpaf** [comment]
@joselitojunior o @vitormalencar só vai dormir hoje se terminar essa parada hahaha

**Comment by vitormalencar** [comment]
kkkkkk ok vou realizar isso antes de ir dormir sim

**Comment by breakzplatform** [comment]
@vitormalencar vergonha

**Comment by thompsonemerson** [comment]
Bora @vitormalencar

**Comment by juarezpaf** [comment]
@joselitojunior @thompsonemerson esquecemos de fechar essa issue, o @vitormalencar já criou o Meetup http://www.meetup.com/Ionic-Ceara/ :rocket:
