### ISSUE TITLE
Adicionar novo artigo

### ISSUE THREAD

**Issue by ftonato** [IonicBrazil/guia-do-desenvolvedor#78]
[Tutorial Ionic – Meu primeiro app](http://tableless.com.br/tutorial-ionic-meu-primeiro-app/) por @grillorafael

**Comment by juarezpaf** [comment]
@ftonato você pode criar um Pull Request adicionando esse tutorial por favor? ;)

**Comment by ftonato** [comment]
Claro o/

**Comment by ftonato** [comment]
Acabei de perceber que fiz na branch _master_, quer que eu altere?
