### ISSUE TITLE
Forma de armazenamento e distribuição de informação

### ISSUE THREAD

**Issue by ftonato** [IonicBrazil/guia-do-desenvolvedor#86]
Olá pessoal,
Normalmente acompanho alguns repositórios que acho interessantes, e percebi que a maioria tem adotado um site (gh-pages) p/ guardar as informações ou p/ ter um link (bonito) de algo quando querem divulgar.
Em algum momento já pensaram em fazer algo do tipo? (Contendo o mesmo material só que organizado de uma forma mais _dinâmica_)

Se eu falei besteira, desconsidere a issue :dancers:

**Comment by ftonato** [comment]
Antes que venham as respostas, eu tenho em mente que existe esse http://ionicbrazil.com/ mas ele não contem as informações de fato, ainda que tenha os links p/ os projetos

**Comment by juarezpaf** [comment]
@f0ntana queremos melhorar muito o site do Ionic Brazil, o problema maior realmente é encontrar colaboradores. :(
Conta para gente o que você tem em mente. :smiley:

**Comment by f0ntana** [comment]
@ftonato @juarezpaf não sou eu mas estamos com você, a correria do dia a dia as vezes nos mata em muitas coisas.

**Comment by ftonato** [comment]
@juarezpaf @f0ntana legal :)
Bom, eu tenho em mente separar ele por tópicos (categorias), assim como está na página README.

Penso em manter os tópicos separados, dando destaque sempre ao último adicionado sendo que cada um "link" do tópico seria uma página, por exemplo:

**Artigos** (categoria)
_Instalando ambiente para desenvolver com Ionic por @fabiorogeriosj_
(Aqui nesse ponto, ficariam os outros tópicos relacionados a artigos, cada qual com seu respectivo link)

Ao abrir a "postagem" poderíamos dar uma descrição um pouco melhor sobre o material, e então adicionar o link de fato, adicionando também botões p/ compartilhar e os comentários.

Essa é a ideia geral, além do que, imagino que um site (tem mais visibilidade) que um repositório, pois como disse, teríamos um link legal p/ distribuir.

Ainda na ideia, penso em toda vez que fosse adicionado uma nova postagem, ele auto publicar nas redes sociais e quem sabe até notificar por e-mail aqueles que fosse cadastrado na newsletter (sim haveria uma newsletter haha)

Poderíamos usar o Jekyll e integrar com Travis CI :]
Me disponho a ajudar com tudo isso, mas apesar de eu ter ideia do layout, eu não não sei desenhar, haveria alguém que poderia nos ajudar nessa parte?

**Comment by ftonato** [comment]
E aí galera, beleza?

Estava aqui percorrendo as **issues** quando em deparei com essa =)
Alguém tem alguma posição?
A dias vi um layout bacana, que poderíamos utilizar, ele é bem simples e podería ser útil para melhor separar os conteúdos, segue o [repositório do template](https://github.com/willianjusten/cards-jekyll-template).

//cc @juarezpaf @f0ntana

**Comment by ftonato** [comment]
Podemos abrir novamente a _issue_ se necessário.

Fico a disposição!
