### ISSUE TITLE
Melhor organização do Readme

### ISSUE THREAD

**Issue by ttibau** [IonicBrazil/guia-do-desenvolvedor#93]
Olá senhores, ainda estou aprendendo a utilizar o github, o conceito de contribuições, de pull request, issue é tudo muito novo. Então peço que relevem qualquer ignorância de minha parte. Estive lendo o Readme que contém as informações do guia do desenvolvedor e gostaria de sugerir um modelo que ao meu ver é mais prático. 
O modelo que eu gostaria de sugerir é parecido com esse: https://github.com/felinalabs/ror-resources 
Claro que isso seria para **apenas algumas partes** do readme, ao meu ver fica bem mais **legível**. Me disponho a fazer caso seja aceito.
Me perdoem qualquer coisa, a minha intenção é apenas contribuir pra tornar a comunidade mais concreta possível!

**Comment by breakzplatform** [comment]
@ttibau interessante sua proposta. Você poderia fazer um fork (sem pull request, ao menos por ora) e demonstrar melhor como funcionaria sua ideia?

**Comment by ttibau** [comment]
@joselitojunior1 Sem problemas, estou estudando o github ainda pra ver como posso colaborar, mas isso é bem rápido haha! vou fazer as alteraçōes aqui.

**Comment by ttibau** [comment]
https://github.com/ttibau/guia-do-desenvolvedor
Fica o link das modificações, qualquer coisa estou aí!

**Comment by juarezpaf** [comment]
@ttibau curti essa proposta. Pode enviar o Pull Request :100:

**Comment by ttibau** [comment]
Feito! Fico feliz que você tenha gostado! Tornar a comunidade sólida é meu objetivo!
