### ISSUE TITLE
Link offline

### ISSUE THREAD

**Issue by ttibau** [IonicBrazil/guia-do-desenvolvedor#94]
Olá senhores, venho informar que o link para um artigo está offline, solicito correcao ou exclusao dele:
http://nicholasess.com.br/desenvolvimento/criando-aplicativo-com-ionic-framework-serie/
Perdoem-me qualquer ignorancia, github é algo totalmente novo pra mim

**Comment by juarezpaf** [comment]
@ttibau valeu cara. Entrei em contato com o autor para saber o que aconteceu, assim que tiver resposta atualizo aqui. o/

**Comment by ttibau** [comment]
Acredito que com o tempo que tem ele não irá colocar no ar novamente, procurei o contato dele no site, porém não encontrei, to fechando a issue e removendo o link, caso consigamos novamente, é só repormos! 

#98
